#!/usr/bin/env python3
"""Writes docs/maps/prop_models.md: every map prop model, its internal name and where it is used.

    tools/scripts/make_prop_model_catalog.py > docs/maps/prop_models.md
"""
import collections
import json
import pathlib
import re
import struct

import g3d_sources

ROOT = pathlib.Path(__file__).resolve().parents[2]
MODELS = ROOT / 'res/field/props/models'


def nsbmd_model_name(blob: bytes) -> str:
    """Name of the first model in an NSBMD's MDL0 dictionary."""
    mdl0, = struct.unpack_from('<I', blob, 16)
    dictionary = mdl0 + 8
    count = blob[dictionary + 1]
    # u8 dummy, u8 count, u16 size | u16, u16, u32 (tree header), 4 * count | u16 entry size, u16 | entries | names
    entries = dictionary + 4 + 8 + 4 * count
    entry_size, = struct.unpack_from('<H', blob, entries)
    names = entries + 4 + entry_size * count
    return blob[names:names + 16].rstrip(b'\0').decode('ascii')


def main():
    order = [line.strip() for line in (MODELS / 'map_prop_models.order').read_text().splitlines() if line.strip()]
    names = [f.rsplit('.', 1)[0] + '_nsbmd' for f in order]
    internal = [nsbmd_model_name(g3d_sources.read_bytes(MODELS / f, ROOT / 'build' / 'g3d_sources')) for f in order]

    used_in = collections.defaultdict(set)
    for path in sorted((ROOT / 'res/field/maps/data').glob('map_*.json')):
        for prop in json.loads(path.read_text(encoding='utf-8'))['props']:
            used_in[prop['model']].add(path.stem.upper())
    in_sets = collections.Counter()
    for path in sorted((ROOT / 'res/field/props/model_sets').glob('*.json')):
        in_sets.update(json.loads(path.read_text(encoding='utf-8'))['mapPropModels'])

    # Which place a cN_/tN_ internal prefix stands for, by majority over the maps using it.
    places = collections.defaultdict(collections.Counter)
    for name, model in zip(names, internal):
        prefix = re.match(r'([ct][1-9]\d*)_', model)
        for map_name in used_in.get(name, ()) if prefix else ():
            place = re.match(r'MAP_((?:[A-Z]+_)*?(?:CITY|TOWN|AREA|LEAGUE))', map_name)
            if place:
                places[prefix.group(1)][place.group(1)] += 1

    print('# Map prop models\n')
    print('Every model in `res/field/props/models` (`build_model.narc`), in archive order. Map')
    print('JSON files refer to a model by the name in the second column. A prop only renders')
    print("if its model is also in the area's prop model set (`res/field/props/model_sets`,")
    print('picked by `res/field/area_data`); "Sets" counts how many sets include it.\n')
    print('The internal name is the one Game Freak gave the model. Common parts: `pc` Pokémon')
    print('Center, `fs` Poké Mart ("Friendly Shop"), `gym`, `kanban` sign, `door`, `tree`.')
    print('`cN_`/`tN_` prefixes mark the city/town a model was made for:\n')
    for prefix in sorted(places, key=lambda p: (p[0], int(p[1:]))):
        print(f'- `{prefix}_`: {places[prefix].most_common(1)[0][0].replace("_", " ").title()}')
    print('\nGenerated by `tools/scripts/make_prop_model_catalog.py`; see `docs/maps/editing_maps.md`.\n')
    print('| # | Name in map JSON | Internal name | Used by maps | Sets |')
    print('| --- | --- | --- | --- | --- |')
    for i, (name, model) in enumerate(zip(names, internal)):
        maps = sorted(used_in.get(name, ()))
        shown = ', '.join(f'`{m}`' for m in maps[:3]) + (f' (+{len(maps) - 3} more)' if len(maps) > 3 else '')
        print(f'| {i} | `{name}` | `{model}` | {shown or "–"} | {in_sets[name]} |')


if __name__ == '__main__':
    main()
