# Each map is a JSON file (tile collision/behaviors, map props, BDHC height plates)
# plus the NSBMD terrain model it names, found in ../models. See docs/maps/editing_maps.md.
map_data_bin_gen = generator(
    map_data_py,
    arguments: [
        '@INPUT@',
        '@OUTPUT@',
        '--depfile', '@DEPFILE@',
        '--models-dir', meson.current_source_dir() / '..' / 'models',
        '--tile-behaviors', meson.project_source_root() / 'include' / 'constants' / 'field' / 'map_tile_behaviors.h',
        '--map-prop-model-naix', map_prop_model_narc[1].full_path(),
    ],
    output: '@BASENAME@.bin',
    depfile: '@BASENAME@.bin.d',
    depends: [ map_prop_model_narc[1] ],
)

map_data_srcs = files(
    'map_data_000.json',
    'map_data_001.json',
    'map_data_002.json',
    'map_data_003.json',
    'map_data_004.json',
    'map_data_005.json',
    'map_data_006.json',
    'map_data_007.json',
    'map_data_008.json',
    'map_data_009.json',
    'map_data_010.json',
    'map_data_011.json',
    'map_data_012.json',
    'map_data_013.json',
    'map_data_014.json',
    'map_data_015.json',
    'map_data_016.json',
    'map_data_017.json',
    'map_data_018.json',
    'map_data_019.json',
    'map_data_020.json',
    'map_data_021.json',
    'map_data_022.json',
    'map_data_023.json',
    'map_data_024.json',
    'map_data_025.json',
    'map_data_026.json',
    'map_data_027.json',
    'map_data_028.json',
    'map_data_029.json',
    'map_data_030.json',
    'map_data_031.json',
    'map_data_032.json',
    'map_data_033.json',
    'map_data_034.json',
    'map_data_035.json',
    'map_data_036.json',
    'map_data_037.json',
    'map_data_038.json',
    'map_data_039.json',
    'map_data_040.json',
    'map_data_041.json',
    'map_data_042.json',
    'map_data_043.json',
    'map_data_044.json',
    'map_data_045.json',
    'map_data_046.json',
    'map_data_047.json',
    'map_data_048.json',
    'map_data_049.json',
    'map_data_050.json',
    'map_data_051.json',
    'map_data_052.json',
    'map_data_053.json',
    'map_data_054.json',
    'map_data_055.json',
    'map_data_056.json',
    'map_data_057.json',
    'map_data_058.json',
    'map_data_059.json',
    'map_data_060.json',
    'map_data_061.json',
    'map_data_062.json',
    'map_data_063.json',
    'map_data_064.json',
    'map_data_065.json',
    'map_data_066.json',
    'map_data_067.json',
    'map_data_068.json',
    'map_data_069.json',
    'map_data_070.json',
    'map_data_071.json',
    'map_data_072.json',
    'map_data_073.json',
    'map_data_074.json',
    'map_data_075.json',
    'map_data_076.json',
    'map_data_077.json',
    'map_data_078.json',
    'map_data_079.json',
    'map_data_080.json',
    'map_data_081.json',
    'map_data_082.json',
    'map_data_083.json',
    'map_data_084.json',
    'map_data_085.json',
    'map_data_086.json',
    'map_data_087.json',
    'map_data_088.json',
    'map_data_089.json',
    'map_data_090.json',
    'map_data_091.json',
    'map_data_092.json',
    'map_data_093.json',
    'map_data_094.json',
    'map_data_095.json',
    'map_data_096.json',
    'map_data_097.json',
    'map_data_098.json',
    'map_data_099.json',
    'map_data_100.json',
    'map_data_101.json',
    'map_data_102.json',
    'map_data_103.json',
    'map_data_104.json',
    'map_data_105.json',
    'map_data_106.json',
    'map_data_107.json',
    'map_data_108.json',
    'map_data_109.json',
    'map_data_110.json',
    'map_data_111.json',
    'map_data_112.json',
    'map_data_113.json',
    'map_data_114.json',
    'map_data_115.json',
    'map_data_116.json',
    'map_data_117.json',
    'map_data_118.json',
    'map_data_119.json',
    'map_data_120.json',
    'map_data_121.json',
    'map_data_122.json',
    'map_data_123.json',
    'map_data_124.json',
    'map_data_125.json',
    'map_data_126.json',
    'map_data_127.json',
    'map_data_128.json',
    'map_data_129.json',
    'map_data_130.json',
    'map_data_131.json',
    'map_data_132.json',
    'map_data_133.json',
    'map_data_134.json',
    'map_data_135.json',
    'map_data_136.json',
    'map_data_137.json',
    'map_data_138.json',
    'map_data_139.json',
    'map_data_140.json',
    'map_data_141.json',
    'map_data_142.json',
    'map_data_143.json',
    'map_data_144.json',
    'map_data_145.json',
    'map_data_146.json',
    'map_data_147.json',
    'map_data_148.json',
    'map_data_149.json',
    'map_data_150.json',
    'map_data_151.json',
    'map_data_152.json',
    'map_data_153.json',
    'map_data_154.json',
    'map_data_155.json',
    'map_data_156.json',
    'map_data_157.json',
    'map_data_158.json',
    'map_data_159.json',
    'map_data_160.json',
    'map_data_161.json',
    'map_data_162.json',
    'map_data_163.json',
    'map_data_164.json',
    'map_data_165.json',
    'map_data_166.json',
    'map_data_167.json',
    'map_data_168.json',
    'map_data_169.json',
    'map_data_170.json',
    'map_data_171.json',
    'map_data_172.json',
    'map_data_173.json',
    'map_data_174.json',
    'map_data_175.json',
    'map_data_176.json',
    'map_data_177.json',
    'map_data_178.json',
    'map_data_179.json',
    'map_data_180.json',
    'map_data_181.json',
    'map_data_182.json',
    'map_data_183.json',
    'map_data_184.json',
    'map_data_185.json',
    'map_data_186.json',
    'map_data_187.json',
    'map_data_188.json',
    'map_data_189.json',
    'map_data_190.json',
    'map_data_191.json',
    'map_data_192.json',
    'map_data_193.json',
    'map_data_194.json',
    'map_data_195.json',
    'map_data_196.json',
    'map_data_197.json',
    'map_data_198.json',
    'map_data_199.json',
    'map_data_200.json',
    'map_data_201.json',
    'map_data_202.json',
    'map_data_203.json',
    'map_data_204.json',
    'map_data_205.json',
    'map_data_206.json',
    'map_data_207.json',
    'map_data_208.json',
    'map_data_209.json',
    'map_data_210.json',
    'map_data_211.json',
    'map_data_212.json',
    'map_data_213.json',
    'map_data_214.json',
    'map_data_215.json',
    'map_data_216.json',
    'map_data_217.json',
    'map_data_218.json',
    'map_data_219.json',
    'map_data_220.json',
    'map_data_221.json',
    'map_data_222.json',
    'map_data_223.json',
    'map_data_224.json',
    'map_data_225.json',
    'map_data_226.json',
    'map_data_227.json',
    'map_data_228.json',
    'map_data_229.json',
    'map_data_230.json',
    'map_data_231.json',
    'map_data_232.json',
    'map_data_233.json',
    'map_data_234.json',
    'map_data_235.json',
    'map_data_236.json',
    'map_data_237.json',
    'map_data_238.json',
    'map_data_239.json',
    'map_data_240.json',
    'map_data_241.json',
    'map_data_242.json',
    'map_data_243.json',
    'map_data_244.json',
    'map_data_245.json',
    'map_data_246.json',
    'map_data_247.json',
    'map_data_248.json',
    'map_data_249.json',
    'map_data_250.json',
    'map_data_251.json',
    'map_data_252.json',
    'map_data_253.json',
    'map_data_254.json',
    'map_data_255.json',
    'map_data_256.json',
    'map_data_257.json',
    'map_data_258.json',
    'map_data_259.json',
    'map_data_260.json',
    'map_data_261.json',
    'map_data_262.json',
    'map_data_263.json',
    'map_data_264.json',
    'map_data_265.json',
    'map_data_266.json',
    'map_data_267.json',
    'map_data_268.json',
    'map_data_269.json',
    'map_data_270.json',
    'map_data_271.json',
    'map_data_272.json',
    'map_data_273.json',
    'map_data_274.json',
    'map_data_275.json',
    'map_data_276.json',
    'map_data_277.json',
    'map_data_278.json',
    'map_data_279.json',
    'map_data_280.json',
    'map_data_281.json',
    'map_data_282.json',
    'map_data_283.json',
    'map_data_284.json',
    'map_data_285.json',
    'map_data_286.json',
    'map_data_287.json',
    'map_data_288.json',
    'map_data_289.json',
    'map_data_290.json',
    'map_data_291.json',
    'map_data_292.json',
    'map_data_293.json',
    'map_data_294.json',
    'map_data_295.json',
    'map_data_296.json',
    'map_data_297.json',
    'map_data_298.json',
    'map_data_299.json',
    'map_data_300.json',
    'map_data_301.json',
    'map_data_302.json',
    'map_data_303.json',
    'map_data_304.json',
    'map_data_305.json',
    'map_data_306.json',
    'map_data_307.json',
    'map_data_308.json',
    'map_data_309.json',
    'map_data_310.json',
    'map_data_311.json',
    'map_data_312.json',
    'map_data_313.json',
    'map_data_314.json',
    'map_data_315.json',
    'map_data_316.json',
    'map_data_317.json',
    'map_data_318.json',
    'map_data_319.json',
    'map_data_320.json',
    'map_data_321.json',
    'map_data_322.json',
    'map_data_323.json',
    'map_data_324.json',
    'map_data_325.json',
    'map_data_326.json',
    'map_data_327.json',
    'map_data_328.json',
    'map_data_329.json',
    'map_data_330.json',
    'map_data_331.json',
    'map_data_332.json',
    'map_data_333.json',
    'map_data_334.json',
    'map_data_335.json',
    'map_data_336.json',
    'map_data_337.json',
    'map_data_338.json',
    'map_data_339.json',
    'map_data_340.json',
    'map_data_341.json',
    'map_data_342.json',
    'map_data_343.json',
    'map_data_344.json',
    'map_data_345.json',
    'map_data_346.json',
    'map_data_347.json',
    'map_data_348.json',
    'map_data_349.json',
    'map_data_350.json',
    'map_data_351.json',
    'map_data_352.json',
    'map_data_353.json',
    'map_data_354.json',
    'map_data_355.json',
    'map_data_356.json',
    'map_data_357.json',
    'map_data_358.json',
    'map_data_359.json',
    'map_data_360.json',
    'map_data_361.json',
    'map_data_362.json',
    'map_data_363.json',
    'map_data_364.json',
    'map_data_365.json',
    'map_data_366.json',
    'map_data_367.json',
    'map_data_368.json',
    'map_data_369.json',
    'map_data_370.json',
    'map_data_371.json',
    'map_data_372.json',
    'map_data_373.json',
    'map_data_374.json',
    'map_data_375.json',
    'map_data_376.json',
    'map_data_377.json',
    'map_data_378.json',
    'map_data_379.json',
    'map_data_380.json',
    'map_data_381.json',
    'map_data_382.json',
    'map_data_383.json',
    'map_data_384.json',
    'map_data_385.json',
    'map_data_386.json',
    'map_data_387.json',
    'map_data_388.json',
    'map_data_389.json',
    'map_data_390.json',
    'map_data_391.json',
    'map_data_392.json',
    'map_data_393.json',
    'map_data_394.json',
    'map_data_395.json',
    'map_data_396.json',
    'map_data_397.json',
    'map_data_398.json',
    'map_data_399.json',
    'map_data_400.json',
    'map_data_401.json',
    'map_data_402.json',
    'map_data_403.json',
    'map_data_404.json',
    'map_data_405.json',
    'map_data_406.json',
    'map_data_407.json',
    'map_data_408.json',
    'map_data_409.json',
    'map_data_410.json',
    'map_data_411.json',
    'map_data_412.json',
    'map_data_413.json',
    'map_data_414.json',
    'map_data_415.json',
    'map_data_416.json',
    'map_data_417.json',
    'map_data_418.json',
    'map_data_419.json',
    'map_data_420.json',
    'map_data_421.json',
    'map_data_422.json',
    'map_data_423.json',
    'map_data_424.json',
    'map_data_425.json',
    'map_data_426.json',
    'map_data_427.json',
    'map_data_428.json',
    'map_data_429.json',
    'map_data_430.json',
    'map_data_431.json',
    'map_data_432.json',
    'map_data_433.json',
    'map_data_434.json',
    'map_data_435.json',
    'map_data_436.json',
    'map_data_437.json',
    'map_data_438.json',
    'map_data_439.json',
    'map_data_440.json',
    'map_data_441.json',
    'map_data_442.json',
    'map_data_443.json',
    'map_data_444.json',
    'map_data_445.json',
    'map_data_446.json',
    'map_data_447.json',
    'map_data_448.json',
    'map_data_449.json',
    'map_data_450.json',
    'map_data_451.json',
    'map_data_452.json',
    'map_data_453.json',
    'map_data_454.json',
    'map_data_455.json',
    'map_data_456.json',
    'map_data_457.json',
    'map_data_458.json',
    'map_data_459.json',
    'map_data_460.json',
    'map_data_461.json',
    'map_data_462.json',
    'map_data_463.json',
    'map_data_464.json',
    'map_data_465.json',
    'map_data_466.json',
    'map_data_467.json',
    'map_data_468.json',
    'map_data_469.json',
    'map_data_470.json',
    'map_data_471.json',
    'map_data_472.json',
    'map_data_473.json',
    'map_data_474.json',
    'map_data_475.json',
    'map_data_476.json',
    'map_data_477.json',
    'map_data_478.json',
    'map_data_479.json',
    'map_data_480.json',
    'map_data_481.json',
    'map_data_482.json',
    'map_data_483.json',
    'map_data_484.json',
    'map_data_485.json',
    'map_data_486.json',
    'map_data_487.json',
    'map_data_488.json',
    'map_data_489.json',
    'map_data_490.json',
    'map_data_491.json',
    'map_data_492.json',
    'map_data_493.json',
    'map_data_494.json',
    'map_data_495.json',
    'map_data_496.json',
    'map_data_497.json',
    'map_data_498.json',
    'map_data_499.json',
    'map_data_500.json',
    'map_data_501.json',
    'map_data_502.json',
    'map_data_503.json',
    'map_data_504.json',
    'map_data_505.json',
    'map_data_506.json',
    'map_data_507.json',
    'map_data_508.json',
    'map_data_509.json',
    'map_data_510.json',
    'map_data_511.json',
    'map_data_512.json',
    'map_data_513.json',
    'map_data_514.json',
    'map_data_515.json',
    'map_data_516.json',
    'map_data_517.json',
    'map_data_518.json',
    'map_data_519.json',
    'map_data_520.json',
    'map_data_521.json',
    'map_data_522.json',
    'map_data_523.json',
    'map_data_524.json',
    'map_data_525.json',
    'map_data_526.json',
    'map_data_527.json',
    'map_data_528.json',
    'map_data_529.json',
    'map_data_530.json',
    'map_data_531.json',
    'map_data_532.json',
    'map_data_533.json',
    'map_data_534.json',
    'map_data_535.json',
    'map_data_536.json',
    'map_data_537.json',
    'map_data_538.json',
    'map_data_539.json',
    'map_data_540.json',
    'map_data_541.json',
    'map_data_542.json',
    'map_data_543.json',
    'map_data_544.json',
    'map_data_545.json',
    'map_data_546.json',
    'map_data_547.json',
    'map_data_548.json',
    'map_data_549.json',
    'map_data_550.json',
    'map_data_551.json',
    'map_data_552.json',
    'map_data_553.json',
    'map_data_554.json',
    'map_data_555.json',
    'map_data_556.json',
    'map_data_557.json',
    'map_data_558.json',
    'map_data_559.json',
    'map_data_560.json',
    'map_data_561.json',
    'map_data_562.json',
    'map_data_563.json',
    'map_data_564.json',
    'map_data_565.json',
    'map_data_566.json',
    'map_data_567.json',
    'map_data_568.json',
    'map_data_569.json',
    'map_data_570.json',
    'map_data_571.json',
    'map_data_572.json',
    'map_data_573.json',
    'map_data_574.json',
    'map_data_575.json',
    'map_data_576.json',
    'map_data_577.json',
    'map_data_578.json',
    'map_data_579.json',
    'map_data_580.json',
    'map_data_581.json',
    'map_data_582.json',
    'map_data_583.json',
    'map_data_584.json',
    'map_data_585.json',
    'map_data_586.json',
    'map_data_587.json',
    'map_data_588.json',
    'map_data_589.json',
    'map_data_590.json',
    'map_data_591.json',
    'map_data_592.json',
    'map_data_593.json',
    'map_data_594.json',
    'map_data_595.json',
    'map_data_596.json',
    'map_data_597.json',
    'map_data_598.json',
    'map_data_599.json',
    'map_data_600.json',
    'map_data_601.json',
    'map_data_602.json',
    'map_data_603.json',
    'map_data_604.json',
    'map_data_605.json',
    'map_data_606.json',
    'map_data_607.json',
    'map_data_608.json',
    'map_data_609.json',
    'map_data_610.json',
    'map_data_611.json',
    'map_data_612.json',
    'map_data_613.json',
    'map_data_614.json',
    'map_data_615.json',
    'map_data_616.json',
    'map_data_617.json',
    'map_data_618.json',
    'map_data_619.json',
    'map_data_620.json',
    'map_data_621.json',
    'map_data_622.json',
    'map_data_623.json',
    'map_data_624.json',
    'map_data_625.json',
    'map_data_626.json',
    'map_data_627.json',
    'map_data_628.json',
    'map_data_629.json',
    'map_data_630.json',
    'map_data_631.json',
    'map_data_632.json',
    'map_data_633.json',
    'map_data_634.json',
    'map_data_635.json',
    'map_data_636.json',
    'map_data_637.json',
    'map_data_638.json',
    'map_data_639.json',
    'map_data_640.json',
    'map_data_641.json',
    'map_data_642.json',
    'map_data_643.json',
    'map_data_644.json',
    'map_data_645.json',
    'map_data_646.json',
    'map_data_647.json',
    'map_data_648.json',
    'map_data_649.json',
    'map_data_650.json',
    'map_data_651.json',
    'map_data_652.json',
    'map_data_653.json',
    'map_data_654.json',
    'map_data_655.json',
    'map_data_656.json',
    'map_data_657.json',
    'map_data_658.json',
    'map_data_659.json',
    'map_data_660.json',
    'map_data_661.json',
    'map_data_662.json',
    'map_data_663.json',
    'map_data_664.json',
    'map_data_665.json'
)

map_data_narc = custom_target('land_data.narc',
    output: [
        'land_data.narc',
    ],
    input: map_data_bin_gen.process(map_data_srcs),
    command: [
        nitroarc_exe,
        '--create',
        '--files-from', files('map_data.order'),
        '--file', '@OUTPUT0@',
        '@PRIVATE_DIR@',
    ],
)

nitrofs_files += map_data_narc
